# ========================
# Base configuration
# ========================
base_config:
  model_root: './checkpoints/'        # dossier pour sauvegarder les mod√®les
  logs_root: './logs/'                # dossier pour les logs
  num_workers: 4                      # pour DataLoader
  verbose: 1
  early_stop_patience: 3
  pickle_feature_encoder: True
  save_best_only: True
  eval_steps: null
  debug_mode: False
  seed: 2025
  group_id: user_id
  use_features: null
  feature_specs: null
  feature_config: null
